# This is a basic workflow to help you get started with Actions

name: Pipiline to Production

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Chekear el Repository
        uses: actions/checkout@v3

      # Install NodeJS 
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.0
        with:
          node-version: "18"

       # Install Dependencias
      - name: Install Dependencias
        run: npm install --force

       # Build app to production
      - name: Build App Production
        run: npm run build:prod

        #Depoly to Page
      - name: Configure GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: dist/presta_tools
	env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
